# Clojure CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.9.0
        environment:
          DATABASE_URL: jdbc:postgresql://127.0.0.1/circleci
      - image: circleci/postgres:11-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run:
          name: Waiting for Postgres
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: lein test
